### ISSUE TITLE
error onOcclusion

### ISSUE THREAD

**Issue by C-peng** [mcamplan/DSKCF_CPP#8]
when evaluateocclusion is true,the project dies. what is wrong?

**Comment by C-peng** [comment]
The error on the code"cv::meanStdDev(cv::Mat(frame[1], boundingBoxModified & imageRect), mean, stddev, occluder);", what is the cause?

**Comment by andriiD** [comment]
> The error on the code"cv::meanStdDev(cv::Mat(frame[1], boundingBoxModified & imageRect), mean, stddev, occluder);", what is the cause?

Have you solved the issue? Thanks

**Comment by fsasm** [comment]
I also get the same error. It happens when I walk between the camera and the object that gets tracked, meaning I occlude the object that gets tracked. Here is also a backtrace from gdb (paths and other data are removed).
```
#6  0x00007ffff558ae42 in cv::error(cv::Exception const&) () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.3.3
#7  0x00007ffff558afc4 in cv::error(int, cv::String const&, char const*, char const*, int) () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.3.3
#8  0x00007ffff563a733 in cv::NAryMatIterator::init(cv::Mat const**, cv::Mat*, unsigned char**, int) () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.3.3
#9  0x00007ffff557f179 in cv::meanStdDev(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_InputArray const&) () from /usr/lib/x86_64-linux-gnu/libopencv_core.so.3.3
#10 0x00000000004b901e in OcclusionHandler::onOcclusion (this=this@entry=0x7fffb0094080, frame=..., features=std::vector of length 1, capacity 2 = {...}, boundingBox=...) at OcclusionHandler.cpp:331
#11 0x00000000004b9fe7 in OcclusionHandler::visibleDetect (this=0x7fffb0094080, frame=..., position=...) at OcclusionHandler.cpp:142
#12 0x00000000004ba333 in OcclusionHandler::detect (this=<optimized out>, frame=..., position=...) at OcclusionHandler.cpp:75
#13 0x000000000049c851 in DskcfTracker::update (this=0xd1f980, frame=..., boundingBox=...) at dskcf_tracker.cpp:26
```
